#!/bin/bash

clear

echo What type of trading stratgey do you want to use?
echo 1\) Buy when price increases x% in past y minutes and sell after z minutes.
echo 2\) Buy now and sell if price increases above x%. Check every y minutes.
echo 3\) 

read strat

clear

echo Getting prices...
cryptowatch | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed -r "s/\x0f//g" > prices.txt
btcprice=$(cat prices.txt | awk '{if ($2 ~ /Bitcoin/ && $3 !~ /Cash/) print $5}')
ethprice=$(cat prices.txt | awk '{if ($2 ~ /Ethereum/) print $5}')
liteprice=$(cat prices.txt | awk '{if ($2 ~ /Litecoin/) print $5}')
bchprice=$(cat prices.txt | awk '{if ($2 ~ /Bitcoin/ && $3 ~ /Cash/) print $6}')
dashprice=$(cat prices.txt | awk '{if ($2 ~ /Dash/) print $5}')
rippleprice=$(cat prices.txt | awk '{if ($2 ~ /Ripple/) print $5}')
digiprice=$(cat prices.txt | awk '{if ($2 ~ /Digibyte/) print $5}')
stellarprice=$(cat prices.txt | awk '{if ($2 ~ /Stellar/) print $5}')

clear

echo Select which coin to trade.
echo 1\) Bitcoin \| Current Price: \$$btcprice
echo 2\) Ethereum \| Current Price: \$$ethprice
echo 3\) Litecoin \| Current Price: \$$liteprice
echo 4\) Bitcoin Cash \| Current Price: \$$bchprice 
echo 5\) Dash \| Current Price: \$$dashprice
echo 6\) Ripple \| Current Price: \$$rippleprice
echo 7\) Digibyte \| Current Price: \$$digiprice
echo 8\) Stellar \| Current Price: \$$stellarprice

read x

if [ $strat -eq 2 ]
then
	echo How often do you want to check the price of the coin \(in minutes\)?
	read interval

	echo At what percent increase from the buying price do you want to sell the coin at?
	read percent

fi


if [ $strat -eq 1 -o $strat -eq 2 ]
	then
		if [ $x -eq 1 ]
			then
				if [ $strat -eq 2 ]
					then
						echo How many Bitcoins do you want to purchase?
						read btcbuy
						btcusd=$(echo "scale=2;$btcprice * $btcbuy" | bc )
						newbtcprice=$(cryptowatch | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed -r "s/\x0f//g" | awk '{if (NR == 4) print $5}')
						percentincrease=$(echo "$(echo "scale=2;$newbtcprice - $btcprice" | bc) / $btcprice" | bc )
						while (($(echo "$percentincrease <= $percent" | bc)))
						do
							newbtcprice=$(cryptowatch | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed -r "s/\x0f//g" | awk '{if (NR == 4) print $5}')
							percentincrease=$(echo "$(echo "scale=2;$newbtcprice - $btcprice" | bc) / $btcprice" | bc )
							if (($(echo "$percentincrease >= $percent" | bc)))
								then
									btcsellrevenue=$(echo "scale=2;$newbtcprice * $btcbuy" | bc)
									btcprofit=$(echo "scale=2;$btcsellrevenue - $btcusd" | bc)
									echo You have sold your $btcbuy Bitcoins!
									echo Your profit from this is \$$btcprofit!
							fi
						sleep $(echo "scale=2;$interval * 60" | bc)
						done
						
				fi
		elif [ $x -eq 2 ]
			then
				echo You have selected Ethereum.
		elif [ $x -eq 3 ]
			then
				echo You have selected Litecoin.
		elif [ $x -eq 4 ]
			then
				echo You have selected Bitcoin Cash.
		elif [ $x -eq 5 ]
			then
				echo You have selected Dash.
		elif [ $x -eq 6 ]
			then
				echo You have selected Ripple.
		elif [ $x -eq 7  ]
			then
				echo You have selected Digibyte.
		elif [ $x -eq 8 ]
			then
				echo You have selected Stellar.
		else
			echo Not a valid coin.
		fi
fi
